### ISSUE TITLE
rest/m1/products returns an object instead of an array when only one price is available

### ISSUE THREAD

**Issue by samhamilton** [moqui/mantle-usl#10]
Hi David, 

If you are trying to PUT a single product price, then the returned JSON sends back an object rather than the array that we would expect from where there is only one price to be returned.

```
$ curl -X PUT -u john.doe:moqui -H 'Content-Type: application/json' -d '{"productId":"100052","pseudoId":"100052","productName":"New Product ","description":null,"lastUpdatedStamp":"2016-03-22T08:17:05.000Z","prices":[{"productPriceId":"100101","price":125,"fromDate":"2016-03-21T06:51:00.000Z","lastUpdatedStamp":"2016-03-22T08:17:05.000Z","product":"100052"}]}' 'https://moqui.example.com/rest/m1/products/100052'
{
    "productId": "100052",
    "prices": {
        "productPriceId": "100101"
    }
}
```
What is expected would be an array e.g.
```
{
   "productId": "100052",
   "prices": [
   {
       "productPriceId": "100101"
   }
   ]
}
```

**Comment by jonesde** [comment]
Quick note: this goes through a generic interface based on entity definitions (including the master definition in this case) so it is really an issue in moqui-framework. I'll look into it there.

**Comment by samhamilton** [comment]
Ah ok - thanks David for help!

**Comment by jonesde** [comment]
Tracked down the issue. All parameters (from all sources, there are quite a few, see WebFacadeImpl.getRequestParameters()) used to be canonicalized, which unwrapped single entry lists and arrays (mainly meant for form submissions where single value parameters are sometimes annoyingly and inconsistently wrapped in arrays).

In moqui-framework commit #5ae3805 this is changed so that only certain parameter sources are canonicalized, excluding the JSON parameters.

**Comment by jonesde** [comment]
BTW, on a side note if you expect it to be a create you can leave out the productId for both the Product and ProductPrices (prices) entries. This runs through the entity-auto service runner which keeps track of parent ID fields and populates them automatically if missing in sub-maps.

For example:

curl -X POST -u john.doe:moqui -H 'Content-Type: application/json' -d '{"productName":"New Product","prices":[{"price":125,"fromDate":"2016-03-21T06:51:00.000Z"}]}' 'http://localhost:8080/rest/m1/products'

You can run this over and over with a new product created with a sequenced ID for each request.

**Comment by samhamilton** [comment]
Many thanks David - that fixed price response problem! 

Cheers
Sam
