### ISSUE TITLE
Service post#Invoice in InvoiceAutoPostServices.xml - debitCreditFlag for credit memo

### ISSUE THREAD

**Issue by igorgallingani** [moqui/mantle-usl#102]
debitCreditFlag for credit memo is incorrect.

Example:
https://docs.oracle.com/cd/A60725_05/html/comnls/us/ar/act4trx.htm

**Comment by jonesde** [comment]
Which debitCreditFlag? There are quite a few in the file, and it handles both payable (customer) and receivable (supplier) credit memos.

**Comment by jonesde** [comment]
BTW, this is very new and while I've done a number of tests (including automated tests) some things could be wrong so thank you for looking at this.

**Comment by igorgallingani** [comment]
I think that every debitCreditFlag in the service should be sets based on invoiceTypeEnumId.

**Comment by jonesde** [comment]
Could you be more specific? How does invoiceTypeEnumId fit into this?

**Comment by igorgallingani** [comment]
If I'm not wrong ..... from this article:
https://www.accountingcoach.com/blog/what-is-a-credit-memo
the credit memo is from the SellerCorp to the BuyerCo ....
In the tests code is the opposite:
def "create Customer Credit Memo Invoice"() {
        when:
        Map b2bCredMemoOut = ec.service.sync().name("mantle.account.InvoiceServices.create#Invoice")
                .parameters([fromPartyId:'JoeDist', toPartyId:'ORG_ZIZI_RETAIL', invoiceTypeEnumId:'InvoiceCreditMemo'

from JoeDist to ORG_ZIZI_RETAIL.

So in the post#Invoice service code.....
Inside the statement: 
  
  <if condition="fromPartyAcctgPreference != null">
      .........

when you call the service "mantle.ledger.LedgerServices.create#AcctgTransEntry", maybe you can use something like this: debitCreditFlag:(invoice.invoiceTypeEnumId!='InvoiceCreditMemo'?'C':'D')
The opposite for inside the statement:
  
  <if condition="toPartyAcctgPreference != null">
      .........

**Comment by jonesde** [comment]
The invoice type is for general categorization and AR/AP GL account mapping (one way multiple AR an AP accounts are supported, if desired).

An invoice is always an invoice and between 2 parties, from one and to another. A credit memo is just another type of invoice. If it is a customer credit memo you want it is represented as an invoice where the from party is a customer, ie representing an obligation to a customer or a payable for the organization. In this way it can be applied to a receivable invoice sent to a customer to offset the balance.

The general rule for payments and invoices is that they must have opposite from/to parties for application to be allowed (payment to invoice, payment to payment, invoice to invoice).

**Comment by igorgallingani** [comment]
Thanks.
