### ISSUE TITLE
Error during project update

### ISSUE THREAD

**Issue by igorgallingani** [moqui/mantle-usl#107]
Changing the estimatedStartDate of the project I get the warning if any date is null:
"Project's new start date puts one or more tasks out of date range."

The problems are in the file ProjectServices.xml at rows 136 and 148. Possible solutions:

136:         <if condition="estimatedStartDate != null &amp;&amp; task.actualStartDate != null &amp;&amp; estimatedStartDate &gt; task.actualStartDate">

148:        <if condition="estimatedStartDate != null &amp;&amp; timeEntry.fromDate != null &amp;&amp; estimatedStartDate &gt; timeEntry.fromDate">

**Comment by jonesde** [comment]
I made small changes in commit 67433d5 for this.

Going forward please file requests for support on the new HiveMind instance on moqui.org. For more information about community infrastructure see:

https://www.moqui.org/docs/moqui/Community+Guide

In the near future issues on GitHub will be disabled altogether.
