### ISSUE TITLE
restore#TenantAccess implements 'revoke'?

### ISSUE THREAD

**Issue by eigood** [moqui/mantle-usl#161]
```xml
    <service verb="restore" noun="TenantAccess">
        <implements service="mantle.product.SubscriptionServices.revoke#SubscriptionResourceAccess"/>
```

It's luck that all those interfaces have the same definitions.

**Comment by jonesde** [comment]
Thanks Adam, minor thing and in a deprecated file but these were meant to be examples and copying that could lead to future issues (especially if or when those interfaces are no longer the same).

**Comment by eigood** [comment]
Yeah, it's that "meant to be examples" part; I'm finding good stuff to base things on. :)
