### ISSUE TITLE
Please use "nowTimestamp" instead of ec.user.nowTimestamp"

### ISSUE THREAD

**Issue by eigood** [moqui/mantle-usl#182]
https://github.com/moqui/mantle-usl/blob/9d46e1ee0bb6bd1b652e4600e3afface48f83443/service/mantle/product/SubscriptionServices.xml#L144

The rest of the lines in this method use nowTimestamp, which is a local variable.  Calling ec.user.nowTimestamp creates a *new* value each time.  This was changed when the MR we submitted was slightly refactored.

**Comment by jonesde** [comment]
This issue confuses me, there is no local nowTimestamp field in that service, though I see you added one in your related PR, #183, so I'll just close this... feel free to reopen if I'm reading this wrong.
