### ISSUE TITLE
Swagger service error with mantle entity ContactMechPurpose

### ISSUE THREAD

**Issue by locnguyenx** [moqui/mantle-usl#20]
I got this issue while trying builtin swagger UI to discover REST service in Moqui: http://localhost:8080/rest/service.swagger/mantle.json
`
No field found for path parameter partyId in entity mantle.party.contact.ContactMechPurpose
`
The same issue occured with the Moqui demo site at: https://demo.moqui.org/rest/service.swagger/mantle.json

**Comment by jonesde** [comment]
Looks like this is related to commit ffe053be436d502bc0ed9c8f30d7018859a8893f

These shouldn't be under the partyId, and in fact would be better under parties/contactMechs. I'm moving these from parties/{partyId}/contactMechPurposes where there is this issue, and not the best organization, to parties/contactMechs/purposes.

**Comment by jonesde** [comment]
This is fixed in commit #7472323
