### ISSUE TITLE
default-value="1" for InvoiceItem.quantity in mantle.invoice.invoice.InvoiceSummary

### ISSUE THREAD

**Issue by mrovnanik** [moqui/mantle-usl#21]
InvoiceSummary view-entity is missing a default value of 1 (for quantity) in calculation of grandTotal (= IITM.quantity \* IITM.amount). Returns Null value.

default-value="1" seems to be a good fit

Line 79 in https://github.com/moqui/mantle-usl/blob/master/entity/AccountingAccountViewEntities.xml.

![image](https://cloud.githubusercontent.com/assets/14863763/15776299/078011d8-2987-11e6-9d43-16d515f9896a.png)

**Comment by jonesde** [comment]
The InvoiceSummary view-entity has been changed dramatically in the current code now that there is a Invoice.invoiceTotal field (see ReleaseNotes.txt in mantle-usl for details) and this is addressed through that.
