### ISSUE TITLE
Bug with service mantle.work.WorkEffortServices.get#WorkEffortStartEnd

### ISSUE THREAD

**Issue by locnguyenx** [moqui/mantle-usl#3]
This exception occurs when creating Event from AssetCalendar screen in PopCommerce Admin module, in which any duration related field left blank:
```
Error running service [mantle.work.WorkEffortServices.get#WorkEffortStartEnd] (message): Field cannot be empty (for field amount of service org.m
oqui.impl.BasicServices.convert#Uom
```
Although the source of problem is the Event ifself, I think it's better if the service mantle.work.WorkEffortServices.get#WorkEffortStartEnd should do checking before calling convert.

**Comment by jonesde** [comment]
Fixed in commit #d9b8bd2.
