### ISSUE TITLE
issue with parsing Date to Timestamp

### ISSUE THREAD

**Issue by locnguyenx** [moqui/mantle-usl#33]
I've tested the mantle-usl Testsuite and failed at 2 testcases of **OrderProcureToPayBasicFlow**: "depreciate Fixed Assets",  "sell Depreciated Asset Loss".

Looking to the build result in Travis of upstream repo, all testcases passed.

After debugging into the related services, I find that:
- in "depreciate Fixed Assets", call service `mantle.ledger.AssetAutoPostServices.calculateAndPost#AllFixedAssetDepreciations` with blank `transactionDate`
- inside called service, this param is set as:
`<set field="transactionDate" from="ec.l10n.parseTimestamp((timePeriod.thruDate as String) + ' 12:00:00', '')"/>`

**timePeriod.thruDate** has Date type with is convert to String as '2016-08-31'. Because the TimeZone of my local PC is UTC+7, the **transactionDate** will be the nextDate ('2016-09-01 00:00:00')

As a result, in later service, Moqui can't find the respected **timePeriod**, which cause the next processing failed.

Sugguestion: if we want to default the **transactionDate** as the last date of this period, shouldn't convert **timePeriod.thruDate** into Timestamp using Locale/Timezone. Only copy the Date portion, while let the Time portion at a specific time, i.e 12:00:00

**Comment by jonesde** [comment]
I made a change in commit #86e4852 that will hopefully resolve this. Would you test it and let me know how if it works for you?

The way dates (without time) are represented in Java is a bit of a pain, the java.time classes in Java 8 may improve this especially if some version of JDBC supports them, but for now hopefully this takes care of it.

**Comment by locnguyenx** [comment]
This fix works.
