### ISSUE TITLE
The problme of receiving asset to a new facility

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/mantle-usl#38]
Based on demo data.

I call servcie mantle.product.AssetServices.receive#Asset with folloing input

assetId:DEMO_1_1A
productId:DEMO_1_1
facilityId:MY_NEW_FACILITY
quantity:7

I think the expected result should be a new asset is created. But the current result is only the QOH and ATP of existing asset are updated in db. It seems the asset is received to facility ORG_ZIZI_RETAIL_WH rather than MY_NEW_FACILITY. I don't think this is correct

I am not sure if I am correct.

**Comment by jonesde** [comment]
I think that service is pretty clear, that if you pass an assetId it will update that Asset record. If you don't want to update that Asset record just don't pass an assetId.

Whether it should update the facilityId when updating the Asset record is another question, and IMO it should not. You didn't describe from a business perspective what you are trying to do with that service call, but it seems like what you want is a new Asset record (as mentioned in the description of the assetId field passing it at all is an uncommon scenario).

**Comment by zhangwei1979** [comment]
Hi David, 

The business is we want store same product in 2 facilities. So the expected results in db should be 

assetId:DEMO_1_1A, productId:DEMO_1_1, facilityId:ORG_ZIZI_RETAIL_WH 
assetId:100000,         productId:DEMO_1_1, facilityId:MY_NEW_FACILITY

Hope that makes sense.

Regards,

Wei

**Comment by zhangwei1979** [comment]
I understand now. I should not pass exsiting assetId if a new facilityId is specified. May be we should add a validation in the service.

Sorry for the confusion.

**Comment by jonesde** [comment]
That's correct, don't pass in an assetId (let it generate one). Currently facilityId is required... I'll think more on a way to make that clear, since it is ignored if an assetId is specified (there are other more controlled ways to move an Asset from one facility to another).
