### ISSUE TITLE
Error Accessing REST API

### ISSUE THREAD

**Issue by samhamilton** [moqui/mantle-usl#5]
When I am trying to use the REST API to access different mantle services I keep getting 403 errors, I dont think this is meant to happen for admin users as I spotted https://github.com/moqui/mantle-usl/blob/master/data/MantleSetupData.xml#L20 where the admin group is authorised? 

```
$ curl -X GET -u john.doe:moqui http://localhost:8080/rest/e1/parties
<html><head><title>Error 403</title></head><body bgcolor="#ffffff"><h1>Status Code: 403</h1>Exception: User [john.doe] is not authorized for View on Entity [mantle.party.Party], here is the current artifact stack:
[name:'component://webroot/screen/webroot/rest.xml/e1',type:'AT_XML_SCREEN_TRANS',action:'AUTHZA_VIEW',user:'null',authz:'null',authAction:'null',inheritable:false,runningTime:0]
[name:'component://webroot/screen/webroot/rest.xml',type:'AT_XML_SCREEN',action:'AUTHZA_VIEW',user:'null',authz:'null',authAction:'null',inheritable:false,runningTime:0]
[name:'component://webroot/screen/webroot.xml',type:'AT_XML_SCREEN',action:'AUTHZA_VIEW',user:'null',authz:'null',authAction:'null',inheritable:false,runningTime:0]<br>Stacktrace: <pre>(none)
</pre><br><hr size="1" width="90%"><i>Generated by Winstone Servlet Engine v1.7.0 at Wed Feb 17 15:27:43 CST 2016</i></body></html>
```

Am I missing something? On a separate note I also suppose that errors for the json api should not spit back html? 

Thanks
Sam

**Comment by jonesde** [comment]
It looks like you are calling rest/e1/parties which does direct entity operations (the entity auto REST API), so authz for the particular entity involved is required. The entity auto REST API is very different from the Service REST API that has path authorizations (much like authz for screen paths), and the data you referenced is for the Service REST API.

In the example component there are some entity level permissions for the rest/e1 and rest/m1 interfaces. You can use those as a model for mantle and other entities.
