### ISSUE TITLE
NPE occurs when add product to cart on popc

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/mantle-usl#51]
The error details is below.

_Error in field expression [ec.user.userAccount.partyId] from [null]
Cannot get property 'partyId' on null object_

I think we should change 
`            <parameter name="enteredByPartyId" default="ec.user.userAccount.partyId"/>
`
to
`            <parameter name="enteredByPartyId" default="ec.user.userAccount?.partyId"/>
`
in OrderServices.xml

**Comment by jonesde** [comment]
Thank you, this is fixed in commit #24126b1.
