### ISSUE TITLE
Error running service mantle.party.ContactServices.get#PartyContactInfo

### ISSUE THREAD

**Issue by locnguyenx** [moqui/mantle-usl#53]
An exception is thrown when running this service:
```
java.lang.NullPointerException: Cannot get property 'contactMechId' on null object
     at mantle_party_ContactServices_get_PartyContactInfo.run(mantle_party_ContactServices_get_PartyContactInfo:101) ~[script:?]
```

I found that the problematic code is [L125](https://github.com/moqui/mantle-usl/blob/master/service/mantle/party/ContactServices.xml#L125)

Maybe the correct code should be:
`<set field="emailContactMechId" from="postalAddress.emailContactMechId"/>`

**Comment by jonesde** [comment]
Thank you, this is fixed in commit #aab283a.
