### ISSUE TITLE
Issue with service mantle.order.OrderBulkServices.store#Order

### ISSUE THREAD

**Issue by locnguyenx** [moqui/mantle-usl#67]
1. Error with parseNumber
problematic code: [L178](https://github.com/moqui/mantle-usl/blob/master/service/mantle/order/OrderBulkServices.xml#L178)
```
<set field="curRevision" from="ec.l10n.parseNumber(existingOrder.externalRevision ?: 1, '')"/>
<set field="newRevision" from="ec.l10n.parseNumber(header.externalRevision ?: 1, '')"/>
```
method `parseNumber` accepts param as String, so this code should be

```
<set field="curRevision" from="ec.l10n.parseNumber(existingOrder.externalRevision ?: '1', '')"/>
<set field="newRevision" from="ec.l10n.parseNumber(header.externalRevision ?: '1', '')"/>
```

2. Unexpected result when finding existing Order at [L139](https://github.com/moqui/mantle-usl/blob/master/service/mantle/order/OrderBulkServices.xml#L139)

```
<entity-find entity-name="mantle.order.OrderHeaderAndPart" list="existingOrderList">
                <econditions combine="or">
                    <econdition field-name="externalId" from="header.externalId"/>
                    <econdition field-name="otherPartyOrderId" from="header.otherPartyOrderId"/>
                </econditions>
                <econdition field-name="customerPartyId" from="header.customerPartyId"/>
            </entity-find>
```

Sample data:
<orders orderId="100000" externalId="100000" otherPartyOrderId="" customerPartyId="CustJqp"/>
<orders orderId="100001" externalId="100001" otherPartyOrderId="" customerPartyId="CustJqp"/>

When I call this service with input-params map = [externalId: "100001", customerPartyId: "CustJqp"], I expected to get existing orderId = "100001". However, the result is one with orderId = "100000".

I think that this code snippet should check matching for externalId firstly, else will check if otherPartyOrderId matched (and not null).

I wonder if my test case is not relevant, or I misunderstand how this service works.

**Comment by jonesde** [comment]
I made a change for item #1.

For #2 I'm not sure exactly what you are expected based on the data you have. The externalId on an order is different from the orderId, the externalId is the ID for the order in the system the order is coming from (for example on an EDI exchange it will have its own ID) and may also be different from the order party order ID which might be something like a customer's purchase order ID.

**Comment by jonesde** [comment]
For this to happen the 'header' object passed in would have to have a null header.otherPartyOrderId and the OrderHeader records in the DB would also have to have a null otherPartyOrderId.

I agree that isn't desirable behavior. I updated the service to only look for existing orders if there is a header.externalId or header.otherPartyOrderId and to only filter by each if they are not empty. That should handle this scenario.
