### ISSUE TITLE
Error when running mantle.work.WorkEffortServices.clone#WorkEffort

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/mantle-usl#71]
To reproduce

1. Goto Application ->Tools ->Service ->Service Run
2. Select mantle.work.WorkEffortServices.clone#WorkEffort
3. Fill Base Work Effort ID, for example, HM
4. Click "Run Service"

You will get the error message below.

_Error finding list of WorkEffortContent by (workEffortId = HM (java.lang.String)) AND (((fromDate = null) OR (fromDate <= 2017-05-24 14:21:20.372 (java.sql.Timestamp))) AND ((thruDate = null) OR (thruDate > 2017-05-24 14:21:20.372 (java.sql.Timestamp))))_

Not sure if we should remove  &lt;date-filter/> from &lt;entity-find/> or add  fromDate and thruDate in  WorkEffortContent entity definition.

**Comment by jonesde** [comment]
Thank you, that was old code from before the WorkEffortContent entity was changed to be more like other *Content entities.

This is fixed in commit #d7f64f7 along with some other changes for cloning project type work efforts, which has been on my low priority to do list for a while.
