### ISSUE TITLE
Question about product.amountFixed

### ISSUE THREAD

**Issue by locnguyenx** [moqui/mantle-usl#78]
I'm confused about the meaning of `Product.amountFixed` vs `OrderItem.selectedAmount`:
- amountFixed's description:

> For products with fixed amounts such as gift certificate amounts, rope lengths, etc.

- selectedAmount: as explained in a Linkedin discussion
[When to use the orderItem.selectedAmount?](https://www.linkedin.com/groups/4640689/4640689-6152036233838194688)

From these explanation, I understood that `Product.amountFixed` and`OrderItem.selectedAmount` have the same meaning.

However, in OrderServices.create#OrderItem, there's a comment about difference between `Product.amountFixed` and `OrderItem.selectedAmount` ( [mantle-usl](https://github.com/moqui/mantle/commit/4af2c5cdc747409ca9004df795d7b8bfd1836b9f) )
> Do NOT do this: Product.amountFixed means inherent amount of item included in quantity, not a selected amount!

This comment is already moved out in current version, but selectedAmount is not set from amountFixed too, . So I wonder if we still need to capture `Product.amountFixed` or not, and do we need to add additional field to set `selectedAmount`  in product definition?

**Comment by jonesde** [comment]
No, selectedAmount does not belong on Product, the concept has nothing to do with Product but is rather a field on OrderItem that can be specified for the item to augment the single quantity field. This isn't commonly support in mantle-usl right now, though the field exists on OrderItem and is supported in some places. An example of using it would be a Product that represent a 1 foot length of rope (amountFixed = 1, amount uom = ft) and you want to allow a customer to specify the length of each rope  (selectedAmount) plus how many ropes of that length to order (quantity).
